[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#795548"  # Coffee color
backgroundColor = "#F5F5F5"  # Light gray
secondaryBackgroundColor = "#EFEBE9"  # Light coffee
textColor = "#5D4037"  # Dark coffee for text
font = "sans serif"